import { Router, Request, Response } from "express";

const GHL_API_KEY = "pit-4ceff49d-22c5-42df-bc34-8fb8a6a29fe2";
const GHL_LOCATION_ID = "UGJmliC4GETAgeO6IDXa";
const SLACK_BOT_TOKEN = "xoxb-414532258742-11486505580721-34wVikPoiBR6MR8ZIRLb8hOr";

interface DealershipProperties {
  dealership_name?: string;
  street_address?: string;
  city?: string;
  state?: string;
  zip?: number | string;
  tracking?: string;
  website?: string;
  alias?: string;
  alias_position?: string;
}

interface ProductionProperties {
  production?: string;
  event_start?: string;
  event_end?: string;
  scf_date?: string;
  deal_stage?: string;
  mailer?: string;
  mailer_2?: string;
  mail_count?: number | string;
  job_numbers?: string;
  sales_rep?: string;
  closer?: string;
  greeter?: string;
  price?: { value?: number } | number | string;
}

interface GHLRelation {
  objectKey: string;
  recordId: string;
}

async function fetchDealership(recordId: string): Promise<DealershipProperties | null> {
  try {
    const resp = await fetch(
      `https://services.leadconnectorhq.com/objects/custom_objects.dealerships/records/${recordId}`,
      {
        headers: {
          Authorization: `Bearer ${GHL_API_KEY}`,
          Version: "v3",
        },
      }
    );
    const data = (await resp.json()) as { record?: { properties?: DealershipProperties } };
    return data.record?.properties ?? null;
  } catch {
    return null;
  }
}

export const ghlRouter = Router();

ghlRouter.post("/ghl", async (req: Request, res: Response) => {
  const body = req.body as Record<string, string>;
  const channelId = body.channel_id;
  const channelName = body.channel_name;

  if (!channelId || !channelName) {
    res.status(400).send("Missing channel_id or channel_name");
    return;
  }

  // Acknowledge Slack immediately (must respond within 3s)
  res.status(200).send("");

  try {
    // Step 1: Join the channel
    await fetch("https://slack.com/api/conversations.join", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ channel: channelId }),
    });

    // Step 2: Query GHL for the production record matching the channel name
    const ghlResp = await fetch(
      "https://services.leadconnectorhq.com/objects/custom_objects.production/records/search",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${GHL_API_KEY}`,
          Version: "v3",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          locationId: GHL_LOCATION_ID,
          page: 1,
          pageLimit: 1,
          query: channelName,
        }),
      }
    );

    const ghlData = (await ghlResp.json()) as {
      records?: Array<{ properties: ProductionProperties; relations?: GHLRelation[] }>;
    };

    const record = ghlData.records?.[0];

    let markdown: string;

    if (!record) {
      markdown = `# GHL Production Details\n\n> No production record found for channel \`${channelName}\`.\n\n*Generated by /ghl*`;
    } else {
      const p = record.properties;

      // Step 3: Fetch associated dealership via relations
      const dealershipRelation = record.relations?.find(
        (r) => r.objectKey === "custom_objects.dealerships"
      );
      const d: DealershipProperties = dealershipRelation
        ? (await fetchDealership(dealershipRelation.recordId)) ?? {}
        : {};

      const address = [d.street_address, d.city, d.state, d.zip].filter(Boolean).join(", ");

      // Format date from YYYY-MM-DD to M/D/YYYY
      const fmtDate = (s?: string) => {
        if (!s) return "";
        const parts = s.split("-");
        if (parts.length !== 3) return s;
        return `${parseInt(parts[1])}/${parseInt(parts[2])}/${parts[0]}`;
      };

      // Format tracking/phone to xxx-xxx-xxxx
      const fmtPhone = (s?: string) => {
        if (!s) return "";
        const digits = s.replace(/\D/g, "");
        const d10 = digits.length === 11 && digits[0] === "1" ? digits.slice(1) : digits;
        if (d10.length === 10) return `${d10.slice(0, 3)}-${d10.slice(3, 6)}-${d10.slice(6)}`;
        return s;
      };

      markdown = `# GHL Production Details

## Campaign Info

| Field | Value |
|:---|---|
| **Production** | ${p.production ?? ""} |
| **Dealership** | ${d.dealership_name ?? ""} |
| **Event Start** | ${fmtDate(p.event_start)} |
| **Event End** | ${fmtDate(p.event_end)} |
| **SCF Date** | ${fmtDate(p.scf_date)} |

## Dealership Info

| Field | Value |
|:---|---|
| **Address** | ${address} |
| **Tracking #** | ${fmtPhone(d.tracking)} |
| **Website** | ${d.website ?? ""} |
| **Alias** | ${d.alias ?? ""} |
| **Position** | ${d.alias_position ?? ""} |

## Production Details

| Field | Value |
|:---|---|
| **Mailer** | ${p.mailer ?? ""} |
| **Mailer 2** | ${p.mailer_2 ?? ""} |
| **Mail Count** | ${p.mail_count ?? ""} |
| **Job #** | ${p.job_numbers ?? ""} |

## Team

| Field | Value |
|:---|---|
| **Sales Rep** | ${p.sales_rep ?? ""} |
| **Closer** | ${p.closer ?? ""} |
| **Greeter** | ${p.greeter ?? ""} |

---
*Generated by /ghl*`;
    }

    // Step 4: Create the canvas in the channel
    const canvasResp = await fetch("https://slack.com/api/canvases.create", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        channel_id: channelId,
        title: "Production",
        document_content: {
          type: "markdown",
          markdown,
        },
      }),
    });

    const canvasData = (await canvasResp.json()) as { ok: boolean; error?: string; canvas_id?: string };

    if (canvasData.ok) {
      console.log(`[ghl] Canvas created: ${canvasData.canvas_id} in channel ${channelId}`);
    } else {
      console.error(`[ghl] Canvas creation failed: ${canvasData.error}`);
      await fetch("https://slack.com/api/chat.postMessage", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          channel: channelId,
          text: `⚠️ Could not create GHL canvas: ${canvasData.error}`,
        }),
      });
    }
  } catch (err) {
    console.error("[ghl] Error:", err);
  }
});
