import { Router, Request, Response } from "express";
import { upsertCanvasLog, getCanvasByChannelName } from "./db";

export const GHL_API_KEY = "pit-4ceff49d-22c5-42df-bc34-8fb8a6a29fe2";
export const GHL_LOCATION_ID = "UGJmliC4GETAgeO6IDXa";
export const SLACK_BOT_TOKEN = "xoxb-414532258742-11486505580721-34wVikPoiBR6MR8ZIRLb8hOr";

interface DealershipProperties {
  dealership_name?: string;
  street_address?: string;
  city?: string;
  state?: string;
  zip?: number | string;
  tracking?: string;
  website?: string;
  alias?: string;
  alias_position?: string;
}

interface ProductionProperties {
  production?: string;
  event_start?: string;
  event_end?: string;
  scf_date?: string;
  deal_stage?: string;
  mailer?: string;
  mailer_2?: string;
  mail_count?: number | string;
  job_numbers?: string;
  sales_rep?: string;
  closer?: string;
  greeter?: string;
  price?: { value?: number } | number | string;
}

interface GHLRelation {
  objectKey: string;
  recordId: string;
}

// Format date from YYYY-MM-DD to M/D/YYYY
function fmtDate(s?: string): string {
  if (!s) return "";
  const parts = s.split("-");
  if (parts.length !== 3) return s;
  return `${parseInt(parts[1])}/${parseInt(parts[2])}/${parts[0]}`;
}

// Format tracking/phone to xxx-xxx-xxxx
function fmtPhone(s?: string): string {
  if (!s) return "";
  const digits = s.replace(/\D/g, "");
  const d10 = digits.length === 11 && digits[0] === "1" ? digits.slice(1) : digits;
  if (d10.length === 10) return `${d10.slice(0, 3)}-${d10.slice(3, 6)}-${d10.slice(6)}`;
  return s;
}

export async function fetchDealership(recordId: string): Promise<DealershipProperties | null> {
  try {
    const resp = await fetch(
      `https://services.leadconnectorhq.com/objects/custom_objects.dealerships/records/${recordId}`,
      {
        headers: {
          Authorization: `Bearer ${GHL_API_KEY}`,
          Version: "v3",
        },
      }
    );
    const data = (await resp.json()) as { record?: { properties?: DealershipProperties } };
    return data.record?.properties ?? null;
  } catch {
    return null;
  }
}

export async function fetchProductionRecord(channelName: string): Promise<{
  properties: ProductionProperties;
  relations?: GHLRelation[];
} | null> {
  const resp = await fetch(
    "https://services.leadconnectorhq.com/objects/custom_objects.production/records/search",
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${GHL_API_KEY}`,
        Version: "v3",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        locationId: GHL_LOCATION_ID,
        page: 1,
        pageLimit: 1,
        query: channelName,
      }),
    }
  );
  const data = (await resp.json()) as {
    records?: Array<{ properties: ProductionProperties; relations?: GHLRelation[] }>;
  };
  return data.records?.[0] ?? null;
}

export function buildCanvasMarkdown(
  p: ProductionProperties,
  d: DealershipProperties,
  channelName: string
): string {
  const address = [d.street_address, d.city, d.state, d.zip].filter(Boolean).join(", ");
  return `# GHL Production Details

| Field | Value |
|:---|---|
| **━━━ CAMPAIGN INFO ━━━** | |
| Production | ${p.production ?? ""} |
| Dealership | ${d.dealership_name ?? ""} |
| Event Start | ${fmtDate(p.event_start)} |
| Event End | ${fmtDate(p.event_end)} |
| SCF Date | ${fmtDate(p.scf_date)} |
| **━━━ DEALERSHIP INFO ━━━** | |
| Address | ${address} |
| Tracking # | ${fmtPhone(d.tracking)} |
| Website | ${d.website ?? ""} |
| Alias | ${d.alias ?? ""} |
| Position | ${d.alias_position ?? ""} |
| **━━━ PRODUCTION DETAILS ━━━** | |
| Mailer | ${p.mailer ?? ""} |
| Mailer 2 | ${p.mailer_2 ?? ""} |
| Mail Count | ${p.mail_count ?? ""} |
| Job # | ${p.job_numbers ?? ""} |
| **━━━ TEAM ━━━** | |
| Sales Rep | ${p.sales_rep ?? ""} |
| Closer | ${p.closer ?? ""} |
| Greeter | ${p.greeter ?? ""} |

---
*Generated by /ghl*`;
}

/**
 * Create or update a Slack canvas in a channel.
 * If an existing canvas ID is provided, it is updated in place (no ghost tabs).
 * Otherwise a new canvas is created.
 */
export async function createOrReplaceCanvas(
  channelId: string,
  channelName: string,
  markdown: string,
  existingCanvasId?: string | null
): Promise<string | null> {
  // If we have an existing canvas, update it in place using canvases.edit
  if (existingCanvasId) {
    // First clear all existing content, then set new content
    const editResp = await fetch("https://slack.com/api/canvases.edit", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        canvas_id: existingCanvasId,
        changes: [
          {
            operation: "replace",
            document_content: {
              type: "markdown",
              markdown,
            },
          },
        ],
      }),
    });
    const editData = (await editResp.json()) as { ok: boolean; error?: string };
    if (editData.ok) {
      console.log(`[ghl] Canvas updated in place: ${existingCanvasId} in channel ${channelId}`);
      return existingCanvasId;
    }
    // If edit fails (e.g. canvas was manually deleted), fall through to create a new one
    console.warn(`[ghl] Canvas edit failed (${editData.error}), creating new canvas`);
  }

  const canvasResp = await fetch("https://slack.com/api/canvases.create", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      channel_id: channelId,
      title: "Production",
      document_content: {
        type: "markdown",
        markdown,
      },
    }),
  });

  const canvasData = (await canvasResp.json()) as {
    ok: boolean;
    error?: string;
    canvas_id?: string;
  };

  if (canvasData.ok && canvasData.canvas_id) {
    console.log(`[ghl] Canvas created: ${canvasData.canvas_id} in channel ${channelId}`);
    await upsertCanvasLog(channelId, channelName, canvasData.canvas_id);
    return canvasData.canvas_id;
  } else {
    console.error(`[ghl] Canvas creation failed: ${canvasData.error}`);
    await fetch("https://slack.com/api/chat.postMessage", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        channel: channelId,
        text: `⚠️ Could not create GHL canvas: ${canvasData.error}`,
      }),
    });
    return null;
  }
}

export const ghlRouter = Router();

// POST /slack/ghl — Slack slash command handler
ghlRouter.post("/ghl", async (req: Request, res: Response) => {
  const body = req.body as Record<string, string>;
  const channelId = body.channel_id;
  const channelName = body.channel_name;

  if (!channelId || !channelName) {
    res.status(400).send("Missing channel_id or channel_name");
    return;
  }

  // Acknowledge Slack immediately (must respond within 3s)
  res.status(200).send("");

  try {
    // Join the channel
    await fetch("https://slack.com/api/conversations.join", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${SLACK_BOT_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ channel: channelId }),
    });

    // Fetch production record
    const record = await fetchProductionRecord(channelName);

    let markdown: string;

    if (!record) {
      markdown = `# GHL Production Details\n\n> No production record found for channel \`${channelName}\`.\n\n*Generated by /ghl*`;
    } else {
      const p = record.properties;
      const dealershipRelation = record.relations?.find(
        (r) => r.objectKey === "custom_objects.dealerships"
      );
      const d: DealershipProperties = dealershipRelation
        ? (await fetchDealership(dealershipRelation.recordId)) ?? {}
        : {};
      markdown = buildCanvasMarkdown(p, d, channelName);
    }

    // Get existing canvas ID to replace if present
    const existingCanvasId = await getCanvasByChannelName(channelName);
    await createOrReplaceCanvas(channelId, channelName, markdown, existingCanvasId);
  } catch (err) {
    console.error("[ghl] Error:", err);
  }
});

// POST /ghl-webhook — GHL workflow webhook (fires when production record is updated)
ghlRouter.post("/ghl-webhook", async (req: Request, res: Response) => {
  // Respond immediately so GHL doesn't retry
  res.status(200).send("ok");

  try {
    const payload = req.body as Record<string, string>;
    console.log("[ghl-webhook] Received payload:", JSON.stringify(payload));

    // GHL sends the production name and channel name as custom data fields
    // We expect: production_name (e.g. "2607 Westshore Honda AME")
    // and optionally channel_name (e.g. "2607-westshore-honda-ame")
    // If channel_name not provided, derive it from production_name
    let channelName = payload.channel_name;
    if (!channelName && payload.production_name) {
      channelName = payload.production_name.toLowerCase().replace(/\s+/g, "-");
    }

    if (!channelName) {
      console.warn("[ghl-webhook] No channel_name or production_name in payload — skipping");
      return;
    }

    // Look up the Slack channel ID from our canvas log
    // We need the channel_id to create the canvas — GHL must send it or we derive from DB
    let channelId = payload.channel_id;
    if (!channelId) {
      // Try to get it from our DB (stored when canvas was first created via /ghl)
      const { getDb } = await import("./db");
      const { canvasLog } = await import("../drizzle/schema");
      const { eq } = await import("drizzle-orm");
      const db = await getDb();
      if (db) {
        const rows = await db
          .select()
          .from(canvasLog)
          .where(eq(canvasLog.channelName, channelName))
          .limit(1);
        if (rows.length > 0) {
          channelId = rows[0].channelId;
        }
      }
    }

    if (!channelId) {
      console.warn(`[ghl-webhook] No channel_id found for channel ${channelName} — skipping`);
      return;
    }

    // Fetch fresh production record from GHL
    const record = await fetchProductionRecord(channelName);
    if (!record) {
      console.warn(`[ghl-webhook] No production record found for ${channelName}`);
      return;
    }

    const p = record.properties;
    const dealershipRelation = record.relations?.find(
      (r) => r.objectKey === "custom_objects.dealerships"
    );
    const d: DealershipProperties = dealershipRelation
      ? (await fetchDealership(dealershipRelation.recordId)) ?? {}
      : {};

    const markdown = buildCanvasMarkdown(p, d, channelName);
    const existingCanvasId = await getCanvasByChannelName(channelName);
    await createOrReplaceCanvas(channelId, channelName, markdown, existingCanvasId);

    console.log(`[ghl-webhook] Canvas refreshed for ${channelName}`);
  } catch (err) {
    console.error("[ghl-webhook] Error:", err);
  }
});
