import type { Request, Response } from "express";
import { Router } from "express";
import { buildProductionCanvas } from "./canvas";
import { getRelayConfig } from "./config";
import { getCampaignByChannelName, logRelayAction, upsertCampaign } from "./db";
import { fetchDealership, fetchProductionRecord } from "./ghl";
import { normalizeCampaignChannelName } from "./naming";
import { scheduleCampaignArchive } from "./scheduling";
import { createOrUpdateProductionCanvas, joinSlackChannel } from "./slack";
import { isAuthorizedSlackRequest, redactErrorDetail } from "./security";

type SlackCommandRequest = Request & { rawBody?: string };
type SlackCommandBody = { channel_id?: string; channel_name?: string; user_id?: string };

const slackCommandRouter = Router();

slackCommandRouter.post("/ghl", async (req: SlackCommandRequest, res: Response) => {
  const config = getRelayConfig();
  const authorized = isAuthorizedSlackRequest({
    signingSecret: config.slackSigningSecret,
    timestamp: req.header("x-slack-request-timestamp") ?? undefined,
    signature: req.header("x-slack-signature") ?? undefined,
    rawBody: req.rawBody,
  });
  if (!authorized) {
    res.status(401).send("Unauthorized Slack command");
    return;
  }

  const body = req.body as SlackCommandBody;
  const channelId = body.channel_id?.trim();
  const channelName = body.channel_name ? normalizeCampaignChannelName(body.channel_name) : "";
  if (!channelId || !channelName) {
    res.json({ response_type: "ephemeral", text: "This command needs a Slack channel name and ID." });
    return;
  }

  // Preserve the original command behavior: acknowledge immediately and do
  // the Canvas work after Slack has received its response.
  res.status(200).send("");

  void (async () => {
    try {
      // This is the first operation in the preserved working command. Slack
      // rejects Canvas creation with not_in_channel unless the bot joins first.
      await joinSlackChannel(channelId);
      // The preserved relay intentionally created a Canvas even when the
      // lookup returned no record. Keep that fallback instead of blocking the
      // command on an optional lookup response.
      let production: Awaited<ReturnType<typeof fetchProductionRecord>> = null;
      try {
        production = await fetchProductionRecord(channelName);
      } catch (error) {
        await logRelayAction({ action: "slack_ghl_production_lookup", outcome: "failed", detail: redactErrorDetail(error) });
      }
      const dealershipRelation = production?.relations?.find(relation => relation.objectKey === "custom_objects.dealerships");
      const dealership = dealershipRelation ? await fetchDealership(dealershipRelation.recordId).catch(() => null) : null;
      const existing = await getCampaignByChannelName(channelName);
      const markdown = production
        ? buildProductionCanvas(production.properties, dealership?.properties ?? {})
        : `# GHL Production Details\n\n> No production record found for channel \`${channelName}\`.\n\n*Generated by /ghl*`;
      const canvasId = await createOrUpdateProductionCanvas(channelId, markdown, existing?.canvasId);
      const campaign = await upsertCampaign({
        productionName: production?.properties.production ?? channelName,
        channelName,
        channelId,
        canvasId,
        dealershipRecordId: dealership?.id ?? null,
        dealershipName: dealership?.properties.dealership_name ?? null,
        eventEndDate: production?.properties.event_end ?? null,
      });
      if (campaign.eventEndDate && campaign.archiveStatus !== "scheduled") {
        await scheduleCampaignArchive(channelName);
      }
      await logRelayAction({ campaignId: campaign.id, action: "slack_ghl_channel_link", outcome: "success", detail: production ? "Slack /ghl refreshed the Production Canvas." : "Slack /ghl created the original no-record-found Production Canvas fallback." });
    } catch (error) {
      const detail = redactErrorDetail(error);
      await logRelayAction({ action: "slack_ghl_channel_link", outcome: "failed", detail }).catch(() => undefined);
    }
  })();
});

export { slackCommandRouter };
